<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LaleliKozmetik.BLL\LaleliKozmetik.BLL.csproj" />
    <ProjectReference Include="..\LaleliKozmetik.DAL\LaleliKozmetik.DAL.csproj" />
  </ItemGroup>

</Project>
